# Generated by Django 4.2.16 on 2026-04-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREDIT', 'Credit'), ('PAYMENT', 'Payment'), ('REVERSAL', 'Reversal'), ('REMINDER_SENT', 'Reminder Sent')], max_length=20)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=20)),
                ('party_id', models.UUIDField()),
                ('amount_paisa', models.BigIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('device_id', models.CharField(max_length=255)),
                ('actor_label', models.CharField(blank=True, max_length=255, null=True)),
                ('device_timestamp', models.DateTimeField()),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='shops.shop')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['device_timestamp'],
                'indexes': [models.Index(fields=['shop', 'device_timestamp'], name='idx_event_device_ts'), models.Index(fields=['party_type', 'party_id'], name='idx_event_party'), models.Index(fields=['shop', 'server_timestamp'], name='idx_event_shop_server_ts')],
            },
        ),
    ]
